In [6]:
#1. Write a NumPy program to test whether none of the elements of a given array is zero.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 0])

result = np.all(arr != 0)

print(result)

False


In [5]:
#2. Write a NumPy program to test whether any of the elements of a given array is non-zero.

import numpy as np

arr = np.array([0, 0, 0, 0, 1])

result = np.any(arr != 0)

print(result)

True


In [ ]:
#3. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given 

import numpy as np

# Create two sample arrays
array1 = np.array([1.0, 2.0, 3.0, 4.0])
array2 = np.array([1.0, 2.0001, 2.9999, 4.0])

# Element wise comparison for equality
equal_comparison = np.equal(array1, array2)

# Element wise comparison for equality within a tolerance
tolerance = 0.001
equal_within_tolerance = np.isclose(array1, array2, atol=tolerance)

print("Array 1:", array1)
print("Array 2:", array2)
print("Element wise comparison without tolerance:", equal_comparison)
print("Element wise comparison within tolerance:", equal_within_tolerance)

In [1]:
#4. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.   
import numpy as np

# Create two sample arrays
array1 = np.array([0]*10)

array2 = np.array([5]*10)

array3 = np.array([10]*10)
print(f'the array have 0 :\t{array1}\nthe array have 5:\t{array2}\nthe array have 10:\t{array3}\n')

the array have 0 :	[0 0 0 0 0 0 0 0 0 0]
the array have 5:	[5 5 5 5 5 5 5 5 5 5]
the array have 10:	[10 10 10 10 10 10 10 10 10 10]



In [ ]:
#5. Write a NumPy program to create an array of the integers from 30 to70.  
import numpy as np

# Creating an array of integers from 30 to 70
array = np.arange(30, 71)
print(array)


In [9]:
#6. Write a NumPy program to create a 3x3 identity matrix 
import numpy as np

# Creating a 3x3 identity matrix
identity_matrix = np.eye(4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
#7. Write a NumPy program to generate a random number between 0 and 1  
import numpy as np

# Generating a random number between 0 and 1
random_number = np.random.rand()
print(random_number)


0.837698564588314


In [21]:
#8. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 
import numpy as np

# Generating an array of 15 random numbers from a standard normal distribution
random_numbers = np.random.randn(15)
print(random_numbers)


[-0.02439968 -0.32089048  0.56918007 -0.65712358 -0.58237531  2.43533794
  0.8787705   2.06101484  1.60597087  1.07985092  1.08212296 -0.35689166
 -0.28204763 -0.17215406 -0.26435145]


In [22]:
#9. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.  
import numpy as np

# Creating a vector with values ranging from 15 to 55
vector = np.arange(15, 56)

# Printing all values except the first and last
print(vector[1:-1])


[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [ ]:
#10. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10  
import numpy as np

# Creating a vector of length 5 filled with arbitrary integers from 0 to 10
vector = np.random.randint(0, 11, 5)
print(vector)


In [23]:
#11. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.  
import numpy as np

# Creating a 10x10 matrix filled with zeros
matrix = np.zeros((10, 10))

# Setting the border elements to 1
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1

print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [24]:
#12. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5. 
import numpy as np

# Creating a 5x5 zero matrix
matrix = np.zeros((5, 5))

# Setting the elements on the main diagonal
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])

print(matrix)


[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [25]:
#13. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.  
import numpy as np

# Creating a 4x4 zero matrix
matrix = np.zeros((4, 4))

# Filling the matrix with staggered 0 and 1, with zeros on the main diagonal
for i in range(4):
    for j in range(4):
        if i != j:
            matrix[i, j] = (i + j) % 2

print(matrix)


[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [26]:
#14. Write a NumPy program to save two given arrays into a single file in compressed format (.npz format) and load it.  
import numpy as np

# Creating two arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])

# Saving the arrays into a single compressed file
np.savez_compressed('arrays_compressed.npz', array1=array1, array2=array2)

# Loading the arrays from the compressed file
loaded = np.load('arrays_compressed.npz')
loaded_array1 = loaded['array1']
loaded_array2 = loaded['array2']

print('Array 1:', loaded_array1)
print('Array 2:', loaded_array2)


Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]


In [27]:
#15. Write a NumPy program to create a one-dimensional array of forty pseudo-randomly generated values.
import numpy as np

# Generating a one-dimensional array of forty pseudo-randomly generated values
random_array = np.random.rand(40)

print(random_array)


[0.49416134 0.5248667  0.22188861 0.66830057 0.04543359 0.57806284
 0.47063021 0.63477081 0.0666608  0.11018022 0.73889834 0.88639259
 0.8989799  0.4263643  0.55033815 0.88475207 0.11158039 0.54234322
 0.83134459 0.669679   0.0257901  0.61879075 0.43175784 0.45776777
 0.12910686 0.54806024 0.29842551 0.09553079 0.43340997 0.1423001
 0.0275019  0.81138502 0.8232175  0.12820531 0.80371825 0.32659085
 0.73762219 0.55243495 0.02019534 0.88507979]


In [28]:
#16. Write a NumPy program to extract all numbers from a given array which are less and greater than a specified number.  
import numpy as np

def extract_numbers(array, number):
    # Extracting numbers less than 'number'
    less_than = array[array < number]
    
    # Extracting numbers greater than 'number'
    greater_than = array[array > number]
    
    return less_than, greater_than

# Example usage:
given_array = np.array([10, 20, 30, 40, 50])
specified_number = 25

less_than_numbers, greater_than_numbers = extract_numbers(given_array, specified_number)

print(f"Numbers less than {specified_number}: {less_than_numbers}")
print(f"Numbers greater than {specified_number}: {greater_than_numbers}")


Numbers less than 25: [10 20]
Numbers greater than 25: [30 40 50]
